import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

export const Layout: React.FC<any> = (props) => {
  return (
    <div style={{ display: "flex" }}>
      <Head>
        <title>FE Bootcamp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
          rel="stylesheet"
        />
      </Head>
      <aside className="flex flex-col items-center text-white bg-[#111111] md:w-[20%] w-[40%]">
        <span className="bg-white p-4 rounded-xl mt-20">
          <Image src="/vercel.svg" alt="Vercel Logo" width={80} height={30} />
        </span>

        <ul className="text-white duration-200 ease-linear mt-16 font-bold md:w-3/4 w-full text-xs md:text-base ">
          <li className="block cursor-pointer p-2 hover:bg-gray-800 hover:text-[#64FFDA] rounded mb-8 duration-200 ease-linear">
            <i className="w-8 fas fa-user p-2 bg-gray-800 rounded-full mx-2"></i>
            <Link href="/about">ABOUT ME</Link>
          </li>

          <li className="block cursor-pointer p-2 hover:bg-gray-800 hover:text-[#64FFDA] rounded mb-8 duration-200 ease-linear">
            <i className="w-8 fas fa-briefcase p-2 bg-gray-800 rounded-full mx-2"></i>
            <Link href="/skills">SKILLS</Link>
          </li>

          <li className="block cursor-pointer p-2 hover:bg-gray-800 hover:text-[#64FFDA] rounded mb-8 duration-200 ease-linear">
            <i className="w-8 fas fa-paper-plane p-2 bg-gray-800 rounded-full mx-2"></i>

            <Link href="/projects">PROJECTS</Link>
          </li>
        </ul>
      </aside>
      <main style={{ background: "#ffffff", width: "100%", height: "100%" }}>
        {props.children}
      </main>
    </div>
  );
};
